name: Run Wallapop Bot

on:
  schedule:
    - cron: '0 0 * * *'  # Ejecuta diariamente a medianoche; ajusta según tus necesidades
  workflow_dispatch:  # Permite ejecutar manualmente el flujo de trabajo desde la interfaz de GitHub

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-chromedriver chromium
        pip install -r requirements.txt

    - name: Check environment
      run: |
        python --version
        pip --version
        which chromedriver
        echo $PATH

    - name: Run bot
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        python bot.py
