name: Run Wallapop Bot

on:
  schedule:
    - cron: '0 0 * * *'  # Ejecuta diariamente a medianoche; ajusta según tus necesidades
  workflow_dispatch:  # Permite ejecutar manualmente el flujo de trabajo desde la interfaz de GitHub

jobs:
  run-bot:
    runs-on: ubuntu-latest  # Usa una máquina virtual con Ubuntu

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Actualiza a la última versión disponible (si existe)

    - name: Set up Python
      uses: actions/setup-python@v5  # Actualiza a la última versión disponible (si existe)
      with:
        python-version: '3.11'  # Versión de Python a usar

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run bot
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}  # Variable de entorno para el token del bot
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}  # Variable de entorno para el ID del chat
      run: |
        python bot.py  # Asegúrate de que el nombre del archivo coincida con tu script
